### ISSUE TITLE
Invalid REGEX causing incorrect domain matching

### ISSUE THREAD

**Issue by domainregistrar** [hexonet/whmcs-ispapi-registrar#123]
**Describe the bug**
Regex used to hide firstname/lastname/org field on GetContactDetails is incorrect.

/[.]ca|it|ch|li|se|sg$/i  -- This matches any domains which contain "ch" for example, so "church.org" is incorrectly matched to what should be a string ending in ".ch"

Due to this issue with GetContactDetails, SaveContactDetails ALSO fails due to missing data because the Registrant/OWNERCONTACT0 is not loaded as this code checks if the "First Name" element exists before using the _POST data so ignores the Registrant data provided and fails.

**To Reproduce**
1. Click modify domain from whmcs on any domain which ISN'T one of the intended extensions
2. Observe lack of fields.

**Expected behavior**
Regex/logic should only match against domain strings ENDING IN ".tld"

**Comment by papakai** [comment]
Dear Dan, thanks for reporting, but looks like this is an issue that has already been fixed. See
https://github.com/hexonet/whmcs-ispapi-registrar/blob/master/registrars/ispapi/ispapi.php#L1940

Probably fixed by this commit 2 months ago:
https://github.com/hexonet/whmcs-ispapi-registrar/commit/d84b0b0b68282bf5691672adb050e8e309b9426c

:-)
