### ISSUE TITLE
Disconnected (Verify Username and Password) 530 Authentication failed; OTP

### ISSUE THREAD

**Issue by triptronics** [hexonet/whmcs-ispapi-registrar#128]
We have enabled 2FA for both OT&E and Production. Now we are receiving this unexpected error. Has this been tested or are we missing something? It is a critical issue and it is the only thing right now that is keeping us from production. Contacted support and they still have not responded. Thank you.

Note: We have already updated the ISPAPI registrar module to the latest version from git.

**Comment by triptronics** [comment]
This was resolved by the support team by following the steps outlined here: https://wiki.hexonet.net/wiki/WHMCS_Secure

**Comment by papakai** [comment]
@triptronics 
thanks for getting in touch with us. The article you have mentioned is outdated in point of the listed commands to white-list and needs a review on our side. Please check this section https://github.com/hexonet/whmcs-ispapi-registrar/wiki/Usage-Guide#using-restrictive-role-user in our usage guide.

HTH

**Comment by papakai** [comment]
in addition: WHMCS itself only provides the possibility to deal with a user with deactivated 2FA in the registrar modules. That was one main issue you were reporting. This isn't something that can be changed on our side or even in whmcs itself. it would require to always prompt for an OTP code whenever whmcs uses a registrar module to interact to the appropriate API/backend system behind.
That's why all registrar modules just provide input fields for credentials or alternatively an API token.

**Comment by triptronics** [comment]
> in addition: WHMCS itself only provides the possibility to deal with a `user` or `role user` with deactivated 2FA in the registrar modules. That was one main issue you were reporting. This isn't something that can be changed on our side or even in whmcs itself. it would require to always prompt for an OTP code whenever whmcs uses a registrar module to interact to the appropriate API/backend system behind.
> That's why all registrar modules just provide input fields for credentials or alternatively an API token.

Hi @papakai 
Understood, we wouldn't want to be entering in a 2FA code every time anyways. Where we were thrown off is when it threw the OTP error but there were no resources indicating how to deal with the issue. When you've updated to the latest version of the module, are presented with a username and password, and you are still receiving an OTP error... you get stuck thinking hmm.. do I need to put a 2FA code with the password one-time and it will register etc. We figured that this was tested and we knew for sure there was a way to get around this issue, but again it was just getting to resolving that issue that was not clear as it was not mentioned in GitHub/Wiki (the instructions for setting up a role user is there, but we did not draw the connection to the OTP error as it was implied rather than explicit). None the less, we got it all working now and we are satisfied with the fact that the module accepts all possible commands in WHMCS, that is impressive. Thanks again for your help.

**Comment by papakai** [comment]
Hi @triptronics 

Understood also on my side. In general, it is quite hard to let a customer know why his login doesn't work. The reason is that our API/backend system only returns a generic error code and description for any failing case to harden the login process against hackers. This means that we, on frontend-side, can not tell customers any details about why it exactly failed.

Therefore I have now added a new entry to the FAQ [here](https://github.com/hexonet/whmcs-ispapi-registrar/wiki/FAQs#49-login-failed-in-registrar-module).

The review in the registrar module will then include to just point on that entry. Concerning the ip address output (issue #129), I'll have to check where we can inject this the best.
