### ISSUE TITLE
X-ACCEPT-WHOISTRUSTEE-TAC not supported

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#203]
When trying to register .de domains from WHMCS, the registration fails with this error:
`Invalid attribute value; X-ACCEPT-WHOISTRUSTEE-TAC not supported`

ID protection was enabled, so I tried disabling it - but that's not possible, it seems. After WHMCS reloads the page, it's enabled again.

**Comment by papakai** [comment]
id protection is not supported for .de (or let me say ccTLDs in general).
Please review your Domain Pricing Section accordingly.

**Comment by papakai** [comment]
@DennisSkov nothing else we can do here. I suggest that you just copy'n'paste the AddDomain Command without the `X-ACCEPT-WHOISTRUSTEE-TAC` parameter from Module Log into the "Api Access" Section of our own Frontend at https://account.hexonet.net and execute it. Then mark the case in Module Queue as solved and change the id protection from 1 to 0 in DB.
If your customers have to pay for the id protection, you'll also have to press "recalcute on save" in domain details to get the price recalculated without id protection costs.

HTH

**Comment by papakai** [comment]
Hi @DennisSkov ,

v6.5.0 introduces a new registrar module configuration setting "Sync Id Protection".

![image](https://user-images.githubusercontent.com/229425/128884305-9d5bd7f1-b6f4-4d1d-a0ac-59d4b614e18e.png)

It cares about setting idprotection in tbldomainpricing to 0|1 accordingly at the end of our registrar tld sync integration.
I tested it with .de for example (I set it to 1) and it successfully switched to 0.

HTH

**Comment by DennisSkov** [comment]
Great! You have a solution for everything, it seems :-D

Would it only disable Trustee Service for TLDs that do not support it?

**Comment by papakai** [comment]
Hi @DennisSkov 

First at all, it doesn't touch Trustee Services at all. Trustee Service = Local Presence Service.
I guess, you call it that way because we use the parameter `X-ACCEPT-WHOISTRUSTEE-TAC` for id protection.

Anyways, the process looks as follows:
1) Go to the `Registrar TLD Sync`
2) Click on the HEXONET logo
3) we will load our prices and TLD Configurations for the Sync
4) if the above configuration option is active, we build up a list of tlds supporting our id protection service and update all of them in DB.
5) no need to save prices to DB, our update is already applied

Updating means:
a) just the ones that are assigned to registrar `ispapi` of course
b) setting idprotection to 1 for the ones supporting it
c) setting idprotection to 0 for the other ones

imho a clean solution, but one minor issue that we cannot improve in Registrar TLD Sync: It updates before new prices / TLDs come to DB (if you submit a price update). But, I guess, this is really not that critical.
