### ISSUE TITLE
Upcoming changes to .dk domains

### ISSUE THREAD

**Issue by Amplificator** [hexonet/whmcs-ispapi-registrar#214]
Can we expect this plugin to have an update that includes support for the upcoming changes relating to .dk domains?

More information can be read at DK-Hostmaster: https://www.dk-hostmaster.dk/en/other-news-related-update

**Comment by papakai** [comment]
Hi @Amplificator 

this topic has been addressed and internally escalated. The new nameserver update process is a big topic as it will affect the current DK Model but also the new registrar model. Until yesterday we were not informed about this little detail. This has been escalated to product management and CTOs to assign highest priority to it.
WHMCS won't be ready 'til September 20th, but I expect our backend system to be it. So that you at least will have a tmp. workaround. WHMCS itself needs probably some custom extension as it doesn't support an authinfo token input field in its nameserver form.

HTH

**Comment by Amplificator** [comment]
Let's hope for a smooth transition :)

**Comment by papakai** [comment]
Hope dies last...

Actually, registrations and transfers don't work. Read:
https://www.dk-hostmaster.dk/en/news/delayed-reopening-services

**Comment by Amplificator** [comment]
That link doesn't seem to work anymore as it just links to the front page and the topic isn't in the news feed :)

**Comment by papakai** [comment]
looks like they cleaned it up now...

the technical switch is done at dk hostmaster, if there's something not working on your end, please report it by support ticket and provide domain name +  related module log entry.

Thanks!

**Comment by Amplificator** [comment]
Great :)

To clarify: Everything is working correctly now and we don't have to do anything? If yes, that's perfect as I like not doing stuff :P

**Comment by papakai** [comment]
@Amplificator 
Up to now, yes looks like that. We are waiting for detailed information regarding the new nameserver update process. Actually looks like the old way is still functional (and what we use). After clarification, we will make decisions on when and how to switch to that new model. They probably have a deadline regarding that old way of processing. At least they announced switching to the new way for both worlds - their old system and their new registrar model on the 20th of September. But reality looks different.
Anyways, we will find the right way here and if necessary, we will communicate changes to our DK Resellers.

**Comment by DennisSkov** [comment]
@papakai didn't you use https://ns-update.dk-hostmaster.dk/en for nameserver changes?
That doesn't work anymore, it seems. It will send the request, but when the user needs to accept it, they're told the request is invalid because it contains an incorrenct amount of nameservers (1) while it should contain between 2 and 7.

It no longer auto-detects the other name servers besides the primary nameserver.

Also, nameserver changes to EPP is broken. For XSD > 4.0.0, you will need to send AuthInfo with the request... When you do that, however, the query will fail and say it doesn't expect AuthInfo. It's so stupid. 
I was testing it yesterday, and I got the same error on 100% on the queries I sent. Hours later, I started receiving emails about nameserver change requests... Some of them were delayed by 10 hours.
So, even though our queries failed (even when using the EPP code), the customer was still notified that a change of nameservers had been requested... And guess what? The client will need to login to their DK Hostmaster account and confirm or deny the transfer, just as before. There's no auto ACK. It makes absolutely **no** sense that they introduced EPP code for nameserver changes when it works like this.

I have no idea how it's going to work. IIRC, they initially wanted to release it September month _last_ year, but they kept delaying the release. I'm pretty sure they should've delayed it again.

It's a complete mess, especially since they want to offer registrant and registrar management of the domains. 

Rant over 😅

**Comment by papakai** [comment]
@DennisSkov

Somehow, it sounds like you guys gathered things that were broken over the last days.

There had been some trouble with new regs and transfers, both fixed.

https://ns-update.dk-hostmaster.dk/en -> still works. Ensure having the cookies accepted. We use it also for our integration. That form is by design just dealing with 1 ns. Basically nothing we can change with that page as it is related to DK hostmaster.

> It no longer auto-detects the other name servers besides the primary nameserver.

No idea, about all this tbh. Our integration is based on that page and is still up and working.

In addition, I am a bit lost with your EPP related comment. Where do we have EPP in use in our WHMCS integration?
Our API is of course based on EPP, but out of your scope...

DK Hostmaster had a lot trouble after their launch with timeouts and queuing, resellers may have noticed this with authentication and authorization issues. We had some webscripting issues around your mentioned nameserver page and that's why transfers were broken. But this got fixed. New Regs were not working whenever it was about getting a new contact created at the registry. The extension we used was outdated, but has been already upgraded and thus, new regs are also working again.
The best idea is to give things again a try. If there's still something not working with our integration, please let us know.

Best
Kai
