### ISSUE TITLE
Transfer Log break admin area layout

### ISSUE THREAD

**Issue by andp97-netsons** [hexonet/whmcs-ispapi-registrar#216]
**Describe the bug**
Transfer log added in v7.0.0 break the admin area interface if INFO.WHOISDATA have a long value

**To Reproduce**
1. Go to admin area
2. Open a successful trasfered domain
3. See error

**Screenshots**
<img width="2347" alt="Schermata 2021-10-04 alle 09 55 56" src="https://user-images.githubusercontent.com/80452359/135814667-947f9781-032a-4a76-9520-99dcdbe4bf63.png">

**Context (please complete the following information):**
 - Device: Desktop iMac 27"
 - OS: MacOS 11.6
 - Browser: Firefox 93.0b9
 - WHMCS Version 8.2.1
 - PHP Version 7.3
 - ISPAPI Registrar Module Version v7.1.0

**Comment by papakai** [comment]
Thanks @andp97-netsons for forwarding. May I ask, how the layout breaks? Is it about ending in "width" issues? I'll added this issue into our current week's sprint. For Reference: #**RSRMID-454**

I'll keep you posted.

**Comment by papakai** [comment]
@andp97-netsons If I am right, the domain was still in status "Transfer Pending", otherwise we don't show that information.
Please forward the domain name to my hands related to this issue allowing me to dig deeper. kschwarz at hexonet dot net.
Please still keep using github our our ticket system when reporting bugs. thanks!

**Comment by andp97-netsons** [comment]
Ok, thanks.

**Comment by papakai** [comment]
-> fixed with [v7.1.3](https://github.com/hexonet/whmcs-ispapi-registrar/releases/tag/v7.1.3)
