### ISSUE TITLE
Provide inplace update for all ispapi modules

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-registrar#225]
Hi
Please provide an "Update Now" button to automatically download the updated module from GitHub and extract it in the correct location, instead of manually downloading and moving to the host and extracting and replacing it!
Like WHMCS Update!
![image](https://user-images.githubusercontent.com/24987084/171583267-75e151cb-a79b-45b0-b883-e3576af2124c.png)

**Comment by KaiSchwarz-cnic** [comment]
Hi @HamidRadmani 

we have this idea since a while in our backlog already. It is basically of interest for all modules we offer.
It is easier said than done - cross-module dependencies (to the registrar module, but also to other addons).
In addition, upgrading to a major version often comes with breaking changes. So, it needs also a mechanism to inform about it and to automatically cover things as far as possible.
There are further technical steps we want to make first before diving into this - just because it makes sense and simplifies things for us later on.

So, again thanks for addressing this feature request. I can promise this is part of our backlog. ETA -> unknown.
I'll be closing this GH issue therefore.

For now, there is a potential alternative way covering some auto-update mechanism on resellers-side:

Writing a bash script which is downloading the zip from [here](https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip) using wget or curl and then to remove /modules/registrars/ispapi and to unzip the archive and move contents to your whmcs system
Still, reading the release notes in case of a major version upgrade remains important to identify manual steps for migration (if there are such).

**Comment by KaiSchwarz-cnic** [comment]
Just want to follow-up here. As you eventually noticed, we merged all our repositories into one (except the backorder module and the domain monitoring widget for technical reasons).

That should make it already a lot easier to upgrade - a single archive to extract. Regarding that upgrade wizard: something we still have in backlog.

**Comment by HamidRadmani** [comment]
Wow, Thank you a lot!
