### ISSUE TITLE
.se additional domain fields shown wrong breaks html

### ISSUE THREAD

**Issue by ryuujinos** [hexonet/whmcs-ispapi-registrar#228]
**Describe the bug**
The additional domain fields for .se domains are rendered wrong and breaks following form

```html
div class="form-group">

                                                                    <input class="form-check-input" type="checkbox"
                                           id="tld_se_2_field"
                                           name="domain_fields[se][2]"
                                           value="on"
                                           required="required">
                                    <label for="tld_se_2_field">
                                                                                    Agreement
                                                                            </label>
                                
                            </div>
                                                    <div class="form-group">

                                                                    <label for="tld_se_3_field">
                                                                                    Identification Number
                                                                            </label>
                                    <input type="text" class="form-control" id="tld_se_3_field"
                                           name="domain_fields[se][3]"
                                           placeholder="<div style="text-align:justify"><b>For individuals or companies located in Sweden</b> a valid Swedish personal or organizational number must be stated.<br/><b>For individuals and companies outside of Sweden</b> the ID number (e.g. Civic registration number, company registration number, or the equivalent) must be stated.</div>"
                                           required="required">
                                
                            </div>
                                                    <div class="form-group">

                                                                    <label for="tld_se_4_field">
                                                                                    Registrant VAT ID
                                                                            </label>
                                    <input type="text" class="form-control" id="tld_se_4_field"
                                           name="domain_fields[se][4]"
                                           placeholder=""
                                           >
                                
                            </div>
                                            </div>
```                                                         

**To Reproduce**
1. try to register or transfer a .se domain
2. whe are you prompted for additional domain fields, the html is broken

**Expected behavior**
html tag correctly paired

**Screenshots**
<img width="963" alt="immagine" src="https://user-images.githubusercontent.com/106514593/181723305-0ea723c6-979e-4d96-a8c0-095195d75d2d.png">

**Context (please complete the following information):**
 - WHMCS Version 8.5.1
 - PHP Version 7.3
 - ISPAPI Registrar Module Version 8.5.0

**Comment by KaiSchwarz-cnic** [comment]
Good Morning @ryuujinos !

![image](https://user-images.githubusercontent.com/229425/181728088-b0f686d5-cc50-4027-85b8-866b708caec9.png)

WHMCS Version 8.5.1 and 8.4 tested
PHP Version 7.4
ISPAPI Registrar Module Version 8.5.0

This is looking good on my end!

The DOM generation of additional domain fields is basically part of WHMCS and out of our scope. It could even be a matter of a broken template file in your system. What's the exact template you're using? twenty-one?

Still, just to ensure you're system is correctly set up with our module, please let us go through the below steps:
a) if you have a custom additional fields configuration file in place under `/resources/domains/additionalfields.php`, please remove that file in case you offer all TLDs over us. Otherwise, please remove only the configurations from that file regarding TLDs you offer over us.
b) ensure the language files are correctly installed (as described [here](https://centralnic-reseller.github.io/centralnic-reseller/docs/hexonet/whmcs/whmcs-ispapi-registrar#installing-our-module))

We ship the additional fields configurations with our module, no need for custom configurations for our TLDs.

I'll be in the meanwhile looking for a PHP 7.3 hosted WHMCS container on our end.

Thanks
Kai

**Comment by KaiSchwarz-cnic** [comment]
Even with PHP 7.3 it is looking good on our end:
![image](https://user-images.githubusercontent.com/229425/181737367-05754724-5012-4c7e-8e0f-845b2870c2b2.png)

**Comment by KaiSchwarz-cnic** [comment]
Let me know @ryuujinos, if this still leaves questions or if we can help you digging deeper.

ideas:

* testing with a different browser (we use latest chrome)
* testing in incognito mode

HTH

**Comment by ryuujinos** [comment]
Hi,
I'm sorry for bothering you with this issue. Thanks for your notes. 

actually the issue was due to the way in which the additional domain fields were rendered.

Thanks!
